name: Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false
          miniforge-version: latest
          use-mamba: true

      - name: Install MAGEMin_C
        shell: bash -l {0}
        run: phasetools-julia-setup --install

      - name: Verify environment
        shell: bash -l {0}
        run: phasetools-julia-setup --check

      - name: Run tests
        shell: bash -l {0}
        run: python -m unittest discover tests -v
